### ISSUE TITLE
Missing weight keys

### ISSUE THREAD

**Issue by keqizero** [francescotonini/human-gaze-target-detection-transformer#7]
Hi, thank you for the work, but I met some problems with the evaluation using the provided checkpoints. The same case happens in your another [repository](https://github.com/francescotonini/object-aware-gaze-target-detection). 

If I directly run the evaluation code, it raises key error "state_dict" for both GazeFollow and VideoAttentionTarget datasets. 

Then I manually changed the model key using this code: 
`state_dict = checkpoint['model']`
`new_checkpoint = {}`
`new_checkpoint['state_dict'] = state_dict`

For the GazeFollow model, I also have to add the prefix "net." for every key: 
`
fixed_state_dict = {f"net.{k}": v for k, v in state_dict.items()}
`

But afterwards, I still encounter errors reporting missing keys: 
`
Missing key(s) in state_dict: "net.gaze_watch_outside_embed.layers.0.weight", "net.gaze_watch_outside_embed.layers.0.bias".
 `

I never changed the code. I do not know why this inconsistency exists, but it happens in both [human-gaze-target-detection-transformer](https://github.com/francescotonini/human-gaze-target-detection-transformer) and [object-aware-gaze-target-detection](https://github.com/francescotonini/object-aware-gaze-target-detection) repositories. Could you help me solve the problem? Thank you in advance!

**Comment by francescotonini** [comment]
Hi! I am unable to replicate the issues you are experiencing. When I download the checkpoints from the provided links and run them using the command `python src/eval.py experiment=hgttr_gazefollow ckpt_path=hgttr_gazefollow.pth`, I do not encounter any errors, here's my output:

```text
[2024-12-05 14:40:55,543][__main__][INFO] - Instantiating datamodule <src.datamodules.gazefollow_datamodule.GazeFollowDataModule>
[2024-12-05 14:40:55,706][__main__][INFO] - Instantiating model <src.models.hgttr_module.HGTTRLitModule>
/home/ftonini/.pyenv/versions/gotd/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/ftonini/.pyenv/versions/gotd/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
[2024-12-05 14:40:57,630][src.utils.misc][WARNING] - Skipping query_embed.weight from pretrained weights: shape mismatch (torch.Size([100, 256]) vs torch.Size([20, 256]))
[2024-12-05 14:40:57,630][src.utils.misc][INFO] - Total weights from file: 458
[2024-12-05 14:40:57,630][src.utils.misc][INFO] - Total weights loaded: 457
[2024-12-05 14:40:57,646][src.utils.misc][INFO] - <All keys matched successfully>
[2024-12-05 14:40:57,671][__main__][INFO] - Instantiating loggers...
[2024-12-05 14:40:57,672][src.utils.utils][WARNING] - Logger config is empty.
[2024-12-05 14:40:57,672][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-12-05 14:40:57,694][__main__][INFO] - Starting testing!
...
```

Could you please provide more details about the command you're using?

**Comment by keqizero** [comment]
Hi, I used the exact same command. I will display all the outputs: 

If I run `python src/eval.py experiment=hgttr_gazefollow ckpt_path=weights/hgttr_gazefollow.pth`, the output shows:
```
[2024-12-05 14:50:21,749][__main__][INFO] - Instantiating datamodule <src.datamodules.gazefollow_datamodule.GazeFollowDataModule>
[2024-12-05 14:50:22,378][numexpr.utils][INFO] - Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-05 14:50:22,379][numexpr.utils][INFO] - NumExpr defaulting to 8 threads.
[2024-12-05 14:50:23,127][__main__][INFO] - Instantiating model <src.models.hgttr_module.HGTTRLitModule>
/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
[2024-12-05 14:50:27,398][src.utils.misc][WARNING] - Skipping query_embed.weight from pretrained weights: shape mismatch (torch.Size([100, 256]) vs torch.Size([20, 256]))
[2024-12-05 14:50:27,401][src.utils.misc][INFO] - Total weights from file: 458
[2024-12-05 14:50:27,402][src.utils.misc][INFO] - Total weights loaded: 457
[2024-12-05 14:50:27,420][src.utils.misc][INFO] - <All keys matched successfully>
[2024-12-05 14:50:27,471][__main__][INFO] - Instantiating loggers...
[2024-12-05 14:50:27,473][src.utils.utils][WARNING] - Logger config is empty.
[2024-12-05 14:50:27,474][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/lightning_lite/plugins/environments/slurm.py:167: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python src/eval.py experiment=hgttr_gazefollow ckpt_path=we ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-12-05 14:50:27,885][__main__][INFO] - Starting testing!
Restoring states from the checkpoint path at weights/hgttr_gazefollow.pth
[2024-12-05 14:50:31,079][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/eval.py", line 95, in evaluate
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 757, in test
    return call._call_and_handle_interrupt(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 806, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 961, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 271, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 363, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
KeyError: 'state_dict'
[2024-12-05 14:50:31,099][src.utils.utils][INFO] - Closing loggers...
Error executing job with overrides: ['experiment=hgttr_gazefollow', 'ckpt_path=weights/hgttr_gazefollow.pth']
Traceback (most recent call last):
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/eval.py", line 111, in <module>
    main()
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/eval.py", line 107, in main
    evaluate(cfg)
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/utils/utils.py", line 42, in wrap
    raise ex
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/eval.py", line 95, in evaluate
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 757, in test
    return call._call_and_handle_interrupt(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 806, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 961, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 271, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 363, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
KeyError: 'state_dict'
```

Then I have to modify the model key. The full modification code: 
```
import torch

# Load the checkpoint
checkpoint_path = "weights/hgttr_gazefollow.pth"
checkpoint = torch.load(checkpoint_path)

# Fix the state_dict keys by adding "net." prefix
state_dict = checkpoint['model']  # Assuming the 'model' exists
fixed_state_dict = {f"net.{k}": v for k, v in state_dict.items()}

# Save the updated checkpoint
new_checkpoint = {}
new_checkpoint['state_dict'] = fixed_state_dict
torch.save(new_checkpoint, "weights/hgttr_gazefollow_fixed.pth")
```

Then I run the command `python src/eval.py experiment=hgttr_gazefollow ckpt_path=weights/hgttr_gazefollow_fixed.pth`, the output shows:
```
[2024-12-05 14:53:38,065][__main__][INFO] - Instantiating datamodule <src.datamodules.gazefollow_datamodule.GazeFollowDataModule>
[2024-12-05 14:53:38,759][numexpr.utils][INFO] - Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-12-05 14:53:38,761][numexpr.utils][INFO] - NumExpr defaulting to 8 threads.
[2024-12-05 14:53:39,543][__main__][INFO] - Instantiating model <src.models.hgttr_module.HGTTRLitModule>
/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
[2024-12-05 14:53:43,840][src.utils.misc][WARNING] - Skipping query_embed.weight from pretrained weights: shape mismatch (torch.Size([100, 256]) vs torch.Size([20, 256]))
[2024-12-05 14:53:43,842][src.utils.misc][INFO] - Total weights from file: 458
[2024-12-05 14:53:43,844][src.utils.misc][INFO] - Total weights loaded: 457
[2024-12-05 14:53:43,864][src.utils.misc][INFO] - <All keys matched successfully>
[2024-12-05 14:53:43,912][__main__][INFO] - Instantiating loggers...
[2024-12-05 14:53:43,915][src.utils.utils][WARNING] - Logger config is empty.
[2024-12-05 14:53:43,916][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/lightning_lite/plugins/environments/slurm.py:167: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python src/eval.py experiment=hgttr_gazefollow ckpt_path=we ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-12-05 14:53:44,344][__main__][INFO] - Starting testing!
Restoring states from the checkpoint path at weights/hgttr_gazefollow_fixed.pth
[2024-12-05 14:53:47,541][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/eval.py", line 95, in evaluate
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 757, in test
    return call._call_and_handle_interrupt(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 806, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 961, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 271, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 363, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for HGTTRLitModule:
	Missing key(s) in state_dict: "net.gaze_watch_outside_embed.layers.0.weight", "net.gaze_watch_outside_embed.layers.0.bias". 
[2024-12-05 14:53:47,565][src.utils.utils][INFO] - Closing loggers...
Error executing job with overrides: ['experiment=hgttr_gazefollow', 'ckpt_path=weights/hgttr_gazefollow_fixed.pth']
Traceback (most recent call last):
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/eval.py", line 111, in <module>
    main()
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/eval.py", line 107, in main
    evaluate(cfg)
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/utils/utils.py", line 42, in wrap
    raise ex
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home2020/home/icube/keqichen/code/human-gaze-target-detection-transformer/src/eval.py", line 95, in evaluate
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 757, in test
    return call._call_and_handle_interrupt(
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 806, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 961, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 271, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 363, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home2020/home/icube/keqichen/miniconda3/envs/ptcu117/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for HGTTRLitModule:
	Missing key(s) in state_dict: "net.gaze_watch_outside_embed.layers.0.weight", "net.gaze_watch_outside_embed.layers.0.bias". 
```

Could you please check if the repository is up-to-date to your local one? Or are we using the same weights?

**Comment by francescotonini** [comment]
I just downloaded the repo and started from scratch, and I was able to reproduce the issue. Sorry about that! By replacing `ckpt_path=` with `+model.net_pretraining`, you should be able to evaluate the public checkpoints. However, if you train from scratch and you need to evaluate your checkpoints, you need to use `cktp_path=`. I will update the README to clarify this.

**Comment by keqizero** [comment]
I just tried using `+model.net_pretraining`, and everything seems to work nicely in both repositories. Thank you so much!
